### ISSUE TITLE
toast-snackbar not work with nuxt build

### ISSUE THREAD

**Issue by mean-cj** [eolant/vuetify-toast-snackbar#33]
Hello

toast-snackbar work with only run dev (yarn dev)
run build not work , snackbar not show

**HTML Source from run dev** 
`<div class="v-snack v-application vts v-snack--active v-snack--bottom v-snack--right" role="alert"><div class="v-snack__wrapper success"><div class="v-snack__content"><i aria-hidden="true" class="v-icon notranslate vts__icon v-icon--left mdi mdi-check theme--dark"></i> <div class="vts__message"><div>บันทึก</div> </div> <!----></div></div></div>`

**HTML Source from run build** 
`<v-snackbar timeout="3000" color="success" bottom="true" right="true" role="alert" class="v-application vts"><v-icon dark="" left="" color="" class="vts__icon">  mdi-check </v-icon> <div class="vts__message"><div>Save</div> </div></v-snackbar>`

**nuxt.config.js**
```
plugins: [
    '@plugins/vuetify',
]
```

**plugins/vuetify.js**
```
import Vue from 'vue'
import Vuetify, { VSnackbar, VBtn, VIcon } from 'vuetify/lib'
import VuetifyToast from 'vuetify-toast-snackbar'

Vue.use(Vuetify, {
  components: {
    VSnackbar,
    VBtn,
    VIcon
  }
})
Vue.use(VuetifyToast)
```

**Comment by eolant** [comment]
Take a look at #31 seems like a similar problem

**Comment by kamikazechaser** [comment]
Solution is to add this to your `nuxt.config.js`:

```js
vuetify: {
    treeShake: false
}
```

@eolant However, tree shaking is an important feature, maybe this library is somehow not playing well with the current build settings for vuetify loader in Nuxt. Could there be an alternative way to load this plugin specifically for Nuxt?

cc/ @goraSi

**Comment by loia5tqd001** [comment]
@kamikazechaser  Please look at [this](https://github.com/loia5tqd001/Clone-Netflix-SE215/blob/641d2c5ba125198625f89dcf65068a560f3c394c/web/nuxt.config.js#L73). Am I doing right? 

I still got the text at the bottom of the page instead of the snackbars after adding `treeShaking: false`, here's the screenshot:
![image](https://user-images.githubusercontent.com/31364664/72196992-15249080-344f-11ea-865b-43b2e52a846e.png)

To reproduce the problem, here's the deployed site of mine: https://nostalgic-lichterman-4cf223.netlify.com/watching. To trigger the snack bar, click to the +/- button like in the image below. 
![image](https://user-images.githubusercontent.com/31364664/72196972-d8589980-344e-11ea-9f24-b002ec97e565.png)

Please help me you're able to, thanks in advance

**Comment by kamikazechaser** [comment]
@loia5tqd001 My bad, its `treeShake`. Updated my previous comment.

**Comment by loia5tqd001** [comment]
@kamikazechaser works now, many thanks

**Comment by lef-nicolas** [comment]
I had the same issue and found, I think, a better solution from https://github.com/nuxt-community/vuetify-module/pull/110 and https://github.com/nuxt-community/vuetify-module/issues/109
In your `nuxt.config.js` : 
```js
vuetify: {
     treeShake: {
      components: ['VSnackbar', 'VBtn', 'VIcon']
    }
}
```

At least treeShake will work for other components :)
